create table if not exists "species" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"common_name" VARCHAR,
	"scientific_name" VARCHAR
);

create table if not exists "bird_song" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"fileurl" VARCHAR NOT NULL,
	"vector" NUMERIC[] NOT NULL DEFAULT array[]::numeric[],
    "species_id" INT NOT NULL REFERENCES "species"("id")
);
