create table if not exists "pivot" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"vector" NUMERIC[] NOT NULL DEFAULT array[]::numeric[],
	"level" INT NOT NULL
);

create table if not exists "tree" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"parent_id" INT REFERENCES "tree"("id"),
	"bird_song_id" INT REFERENCES "bird_song"("id"),
	"level" INT NOT NULL,
	"lower_distance" NUMERIC,
	"upper_distance" NUMERIC
);
/* Para calcular distancias, tomar el pivote del nivel actual y buscar la mayor y menor distancia entre 
los otros pivotes. Luego crear intervalos (0, menor_distancia), (mayor_distancia, infinito), y
la cantidad de intervalos deseados de igual tamaño entre menor_distancia y mayor_distancia.
Para cada intervalo se crea un nodo raíz (o hijo de la raíz) y para cada nodo se repite el proceso
con el segundo pivote y así sucesivamente.
*/
